version: "3.8"
services:
  basler_camera:
    build: .
    container_name: basler_camera
    platform: linux/arm64 # Specify runtime platform
    network_mode: host # required for GigE Vision discovery
    privileged: true # raw device/network access
    volumes:
      - ./bags:/catkin_ws/bags:rw # save rosbags locally
    stdin_open: true
    tty: true
